repos:
  # Basic hygiene
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-toml
      - id: check-added-large-files

  # Black for formatting
  - repo: https://github.com/psf/black
    rev: 24.8.0
    hooks:
      - id: black
      # just check src and tests dirs
        files: ^(src|tests)/
        language_version: python3.12  # or whichever version you use

  # Ruff (fast linter; replaces flake8 + more)
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.8
    hooks:
      - id: ruff
        args: [--fix]   # auto-fix what it can

  # mypy type checker
  # - repo: https://github.com/pre-commit/mirrors-mypy
  #   rev: v1.10.0
  #   hooks:
  #     - id: mypy
  #     # only check src dir
  #       files: ^src/
  #       additional_dependencies: [types-PyYAML]
