# Simple test configuration
[scenarios.test_basic]
name = "Basic Test"
description = "Simple test scenario"

[scenarios.test_basic.offense]
formation = "basic"
play = "inside_run"
players = ["middle,backfield,1"]

[scenarios.test_basic.defense]
formation = "basic"
play = "base"
players = ["middle,line,2", "middle,box,1"]
