dice:
  advantage_bonus: 1
  core: 2d6
  disadvantage_penalty: 1
modifiers:
  average_vs_elite: -1
  elite_vs_average: 1
  mismatch_bonus: 2
  perfect_counter: -2
  tactical_advantage: 1
  tactical_disadvantage: -1
outcome_tables:
  deep_pass:
    '10':
      kind: gain
      y:
      - 28
      - 40
    '11':
      kind: gain
      y:
      - 34
      - 48
    '12':
      kind: gain
      y:
      - 40
      - 60
    '2':
      kind: sack
      y:
      - -12
      - -6
    '3':
      kind: sack
      y:
      - -9
      - -4
    '4':
      kind: inc
      y:
      - 0
      - 0
    '5':
      kind: inc
      y:
      - 0
      - 0
    '6':
      kind: gain
      y:
      - 10
      - 16
    '7':
      kind: gain
      y:
      - 14
      - 20
    '8':
      kind: gain
      y:
      - 18
      - 26
    '9':
      kind: gain
      y:
      - 22
      - 32
  draw_play:
    '10':
      kind: gain
      y:
      - 6
      - 13
    '11':
      kind: break
      y:
      - 10
      - 22
    '12':
      kind: break
      y:
      - 12
      - 28
    '2':
      kind: sack
      y:
      - -8
      - -3
    '3':
      kind: sack
      y:
      - -5
      - -2
    '4':
      kind: stuff
      y:
      - -1
      - 1
    '5':
      kind: gain
      y:
      - 0
      - 3
    '6':
      kind: gain
      y:
      - 2
      - 5
    '7':
      kind: gain
      y:
      - 3
      - 7
    '8':
      kind: gain
      y:
      - 4
      - 9
    '9':
      kind: gain
      y:
      - 5
      - 11
  inside_run:
    '10':
      kind: gain
      y:
      - 5
      - 12
    '11':
      kind: break
      y:
      - 8
      - 20
    '12':
      kind: break
      y:
      - 10
      - 30
    '2':
      kind: loss
      y:
      - -5
      - -1
    '3':
      kind: stuff
      y:
      - -3
      - 0
    '4':
      kind: stuff
      y:
      - -2
      - 1
    '5':
      kind: gain
      y:
      - 0
      - 3
    '6':
      kind: gain
      y:
      - 1
      - 4
    '7':
      kind: gain
      y:
      - 2
      - 6
    '8':
      kind: gain
      y:
      - 3
      - 8
    '9':
      kind: gain
      y:
      - 4
      - 10
  outside_run:
    '10':
      kind: gain
      y:
      - 8
      - 15
    '11':
      kind: break
      y:
      - 12
      - 25
    '12':
      kind: break
      y:
      - 15
      - 35
    '2':
      kind: loss
      y:
      - -6
      - -2
    '3':
      kind: loss
      y:
      - -4
      - -1
    '4':
      kind: stuff
      y:
      - -1
      - 2
    '5':
      kind: gain
      y:
      - 1
      - 4
    '6':
      kind: gain
      y:
      - 2
      - 5
    '7':
      kind: gain
      y:
      - 3
      - 7
    '8':
      kind: gain
      y:
      - 4
      - 9
    '9':
      kind: gain
      y:
      - 6
      - 12
  screen_pass:
    '10':
      kind: gain
      y:
      - 11
      - 19
    '11':
      kind: break
      y:
      - 15
      - 30
    '12':
      kind: break
      y:
      - 20
      - 40
    '2':
      kind: loss
      y:
      - -5
      - -1
    '3':
      kind: loss
      y:
      - -3
      - 0
    '4':
      kind: stuff
      y:
      - 0
      - 2
    '5':
      kind: gain
      y:
      - 1
      - 4
    '6':
      kind: gain
      y:
      - 3
      - 7
    '7':
      kind: gain
      y:
      - 5
      - 10
    '8':
      kind: gain
      y:
      - 7
      - 13
    '9':
      kind: gain
      y:
      - 9
      - 16
  short_pass:
    '10':
      kind: gain
      y:
      - 9
      - 16
    '11':
      kind: gain
      y:
      - 10
      - 20
    '12':
      kind: gain
      y:
      - 12
      - 24
    '2':
      kind: sack
      y:
      - -10
      - -5
    '3':
      kind: sack
      y:
      - -7
      - -3
    '4':
      kind: inc
      y:
      - 0
      - 0
    '5':
      kind: inc
      y:
      - 0
      - 0
    '6':
      kind: gain
      y:
      - 3
      - 6
    '7':
      kind: gain
      y:
      - 4
      - 9
    '8':
      kind: gain
      y:
      - 6
      - 12
    '9':
      kind: gain
      y:
      - 7
      - 14
  te_route:
    '10':
      kind: gain
      y:
      - 12
      - 22
    '11':
      kind: gain
      y:
      - 15
      - 28
    '12':
      kind: gain
      y:
      - 18
      - 35
    '2':
      kind: sack
      y:
      - -9
      - -3
    '3':
      kind: sack
      y:
      - -6
      - -2
    '4':
      kind: inc
      y:
      - 0
      - 0
    '5':
      kind: inc
      y:
      - 0
      - 0
    '6':
      kind: gain
      y:
      - 4
      - 8
    '7':
      kind: gain
      y:
      - 6
      - 12
    '8':
      kind: gain
      y:
      - 8
      - 15
    '9':
      kind: gain
      y:
      - 10
      - 18
  rpo:
    '10':
      kind: gain
      decision: pass
      y:
      - 8
      - 15
    '11':
      kind: gain
      decision: pass
      y:
      - 12
      - 20
    '12':
      kind: gain
      decision: pass
      y:
      - 15
      - 25
    '2':
      kind: sack
      decision: pass
      y:
      - -8
      - -3
    '3':
      kind: stuff
      decision: run
      y:
      - -3
      - 1
    '4':
      kind: inc
      decision: pass
      y:
      - 0
      - 0
    '5':
      kind: gain
      decision: run
      y:
      - 1
      - 4
    '6':
      kind: gain
      decision: run
      y:
      - 2
      - 6
    '7':
      kind: gain
      decision: run
      y:
      - 3
      - 8
    '8':
      kind: inc
      decision: pass
      y:
      - 0
      - 0
    '9':
      kind: gain
      decision: pass
      y:
      - 6
      - 12
turnovers:
  pass_interception:
    base: 0.02
    eff3: 0.08
    eff4: 0.05
    eff5: 0.03
    pressure_bonus: 0.02
  run_fumble:
    base: 0.01
    contact_bonus: 0.005
    eff3: 0.04
    eff4: 0.02
weights:
  eff_max: 12
  eff_min: 2
