# resolver_config.yaml
dice:
  # choose global default core roll
  core: "2d6"           # change to "1d10" for flatter spread, "3d6" for tighter bell
  advantage_bonus: 1     # extra die kept when advantage=true (roll 3d6 keep 2 highest)
  disadvantage_penalty: 1

weights:
  # clamp final 'eff' (effective roll + modifiers)
  eff_min: 3
  eff_max: 12

modifiers:
  lane_strength_cap: 2   # clamp lane_mod to [-2,+2]
  blitz_pass_penalty: -1
  blitz_vs_outside_run_bonus: +1
  shell_vs_short: -1     # shell coverage penalties
  shell_vs_deep:  -1
  run_commit_vs_run: -1
  play_action_vs_run_commit: +1
  draw_vs_blitz: +1

turnovers:
  pass_interception:
    base: 0.01
    eff3: 0.03
    eff4: 0.02
    eff5: 0.015
    blitz_lane_bonus: 0.01
  run_fumble:
    base: 0.005
    eff3: 0.03

tables:
  short_pass:
    # eff (post-mod) => outcome band
    "3":   { kind: sack,  y: [-7, -3] }
    "4":   { kind: inc,   y: [0, 0] }
    "5":   { kind: inc,   y: [0, 0] }
    "6":   { kind: gain,  y: [3, 6] }
    "7":   { kind: gain,  y: [4, 9] }
    "8":   { kind: gain,  y: [6, 12] }
    "9":   { kind: gain,  y: [7, 14] }
    "10":  { kind: gain,  y: [9, 16] }
    "11":  { kind: gain,  y: [10, 20] }
    "12":  { kind: gain,  y: [12, 24] }
  deep_pass:
    "3":   { kind: sack,  y: [-9, -4] }
    "4":   { kind: inc,   y: [0, 0] }
    "5":   { kind: inc,   y: [0, 0] }
    "6":   { kind: gain,  y: [10, 16] }
    "7":   { kind: gain,  y: [14, 20] }
    "8":   { kind: gain,  y: [18, 26] }
    "9":   { kind: gain,  y: [22, 32] }
    "10":  { kind: gain,  y: [28, 40] }
    "11":  { kind: gain,  y: [34, 48] }
    "12":  { kind: gain,  y: [40, 60] }
  inside_run:
    "3":   { kind: stuff, y: [-3, 0] }
    "4":   { kind: stuff, y: [-2, 1] }
    "5":   { kind: gain,  y: [0, 3] }
    "6":   { kind: gain,  y: [1, 4] }
    "7":   { kind: gain,  y: [2, 6] }
    "8":   { kind: gain,  y: [3, 8] }
    "9":   { kind: gain,  y: [4, 10] }
    "10":  { kind: gain,  y: [5, 12] }
    "11":  { kind: break, y: [8, 20] }
    "12":  { kind: break, y: [10, 30] }
